## List of all the services
services:

  ## Mandatory Services
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    secrets:
      - mysql_password
      - mysql_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "sh", "-c", "mysqladmin ping -h localhost -u root -p$$(cat /run/secrets/mysql_root_password)"]
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_TITLE=${WP_TITLE}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - WP_USER_PASSWORD_FILE=/run/secrets/wp_user_password
    secrets:
      - mysql_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    expose:
      - "9000"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f php-fpm || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      wordpress:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      static_page:
        condition: service_started
      adminer:
        condition: service_started
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    ports:
      - "443:443"

  ## Bonus Services
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: unless-stopped
    networks:
      - inception_network
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  static_page:
    container_name: static_page
    build: ./requirements/bonus/static_page
    restart: on-failure
    networks:
      - inception_network
    expose:
      - "81"

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception_network
    expose:
      - "8080"

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    restart: on-failure
    environment:
      - FTP_USER=${FTP_USER}
      - PASV_ADDRESS=${DOMAIN_NAME}
    secrets:
      - ftp_user_password
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    ports:
      - "21:21"
      - "21100-21102:21100-21102"

  ctop:
    container_name: ctop
    build: ./requirements/bonus/ctop
    restart: unless-stopped
    tty: true
    depends_on:
      mariadb:
        condition: service_healthy
      wordpress:
        condition: service_healthy
      nginx:
        condition: service_started
      redis:
        condition: service_started
      static_page:
        condition: service_started
      adminer:
        condition: service_started
      ftp:
        condition: service_started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - inception_network

## Secrets Definition
secrets:
  mysql_password:
    file: ./secrets/mysql_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt
  ftp_user_password:
    file : ./secrets/ftp_user_password.txt

## Used volumes
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wordpress

## Network specs
networks:
  inception_network:
    driver: bridge