## List of all the services
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always ##! Un doute à ce niveau
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    ports:
      - "3306:3306" ##! A changer une fois tessts ok

## Used volumes
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

## Network specs
networks:
  inception_network:
    driver: bridge